# -*- coding: utf-8 -*-
"""Studycase-minicourse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JoIIyvacHiiolkVUzDDZ3qUVvS7jUsR7
"""

import pandas as pd

airbnb = pd.read_csv("AB_NYC_2019.csv")
airbnb.info()

airbnb

"""1. Drop Duplicates"""

airbnb=airbnb.drop_duplicates()

airbnb.info()

"""2. Change data type
*Check* the data contents of the last_review column
"""

airbnb['last_review']

airbnb['last_review'] = pd.to_datetime(airbnb['last_review'], format='%Y/%m/%d')

airbnb['last_review']

"""3. Handle Missing Data

The amount of missing data in column last_review is 48895-48874 = 21 where the value is not up to 1% of the overall data.
"""

airbnb[airbnb['host_name'].isna()]

airbnb[~airbnb['host_name'].isna()]

airbnb=airbnb[~airbnb['host_name'].isna()]
airbnb.info()
# tanda ~ artinya NOT

"""Try the missing data on column "name""""

48895-48879

16/48895

48874-48858

16/48874

airbnb[airbnb['name'].isna()]

airbnb[~airbnb['name'].isna()]

airbnb=airbnb[~airbnb['name'].isna()]
airbnb.info()

"""4. Remove outliers
*Can use Boxplot or Scatterplot*
"""

#Before
airbnb.boxplot(column='price')

airbnb['price'].describe()

"""From the boxplot and statistical description of the 'price' column, it can be identified if there are outliers. If in the boxplot, the image of the blox is not visible or very small and from the statistical description the value of Q3 or the 3rd quartile with the maximum value, the distance is very far compared to the distance between the other quartiles.

Batas atas = Q3 + 1.5 x (Q3-Q1)

Batas bawah = Q1 - 1.5 x (Q3-Q1)

Nilai yang melebihi batas atas dan lebih kurang dari batas bawah berati itu adalah Outliers
"""

q1 = airbnb['price'].quantile(0.25)
q3 = airbnb['price'].quantile(0.75)
upper_limit = q3 +  1.5 * (q3-q1)
lower_limit = q1 -  1.5 * (q3-q1)

airbnb = airbnb[airbnb['price'] > lower_limit]
airbnb = airbnb[airbnb['price'] < upper_limit]
airbnb['price'].describe()

#After
airbnb.boxplot(column='price')

airbnb.info()

48858-45882

2976/48858

"""The number of data is now 45882 from before the ourlier was removed. And when compared to 45882 with 48858 it is only 0.060911

Added column "lat,long" from column "latitude"+"longitude"
"""

airbnb['latitude'] = airbnb['latitude'].astype('str')
airbnb['longitude'] = airbnb['longitude'].astype('str')

airbnb['lat,long'] = airbnb['latitude']+","+airbnb['longitude']
airbnb

airbnb.info()

"""To change the data type of column 'id' and 'host_id'"""

airbnb['id'] = airbnb['id'].astype('str')
airbnb['host_id'] = airbnb['host_id'].astype('str')

"""Check the data again to see if there is a typo in the data or not and to check whether there is duplicate data or not"""

airbnb['neighbourhood_group'].unique()

airbnb['room_type'].unique()

"""Save the cleaned table to a csv file"""

airbnb.to_csv('airbnb_cleaned.csv')

from google.colab import files
files.download('airbnb_cleaned.csv')